import type { Resource } from './types'

export const resources: readonly Resource[] = [
    {
        id: 'app-announcements',
        title: 'Reklamy w aplikacji',
        description:
            'Popap przy otwarciu aplikacji dla wszystkich użytkowników. Jeden aktywny harmonogram, ustawiany odstęp między pokazami na urządzeniu. Daty w lokalnej strefie przeglądarki.',
        group: 'Komunikacja',
        path: '/main/resources/app-announcements',
        roles: ['writer'],
        columns: ['title', 'enabled', 'startsAt', 'endsAt', 'intervalMinutes', 'actionType'],
    },
    {
        id: 'subscription-plans',
        title: 'Plany subskrypcji',
        description: 'Wersje planów, limity i okres próbny',
        group: 'Subskrypcje',
        path: '/main/resources/subscription-plans',
        roles: ['admin'],
        columns: [
            'name',
            'code',
            'version',
            'rank',
            'documentsPerMonth',
            'openCases',
            'available',
        ],
    },
    {
        id: 'subscription-prices',
        title: 'Ceny subskrypcji',
        description: 'Produkty Apple, Google i dev powiązane z planami',
        group: 'Subskrypcje',
        path: '/main/resources/subscription-prices',
        roles: ['admin'],
        columns: ['planId', 'provider', 'interval', 'productId', 'available'],
    },
    {
        id: 'user-subscriptions',
        title: 'Symulacja subskrypcji',
        description:
            'Zdarzenia testowe użytkownika; dostępne wyłącznie na serwerze z włączonym trybem deweloperskim',
        group: 'Subskrypcje',
        path: '/main/resources/user-subscriptions',
        roles: ['admin'],
        columns: [],
    },
    {
        id: 'legal-documents',
        title: 'Dokumenty prawne',
        description: 'Aktualne regulaminy i polityki w formacie PDF',
        group: 'Dokumenty prawne',
        path: '/main/resources/legal-documents',
        roles: ['admin'],
        columns: ['title', 'code', 'version', 'isPlaceholder', 'publishedAt'],
    },
    {
        id: 'legal-document-versions',
        title: 'Wersje dokumentów',
        description: 'Przesyłanie szkiców PDF i publikowanie nowych wersji',
        group: 'Dokumenty prawne',
        path: '/main/resources/legal-document-versions',
        roles: ['admin'],
        columns: ['id', 'version', 'status', 'isPlaceholder', 'publishedAt'],
    },
    {
        id: 'payment-ledger',
        title: 'Rejestr płatności',
        description:
            'Zweryfikowane płatności i zwroty; kwoty w najmniejszych jednostkach waluty',
        group: 'Finanse',
        path: '/main/resources/payment-ledger',
        roles: ['admin'],
        columns: [
            'id',
            'occurredAt',
            'product',
            'kind',
            'amountMinor',
            'currency',
            'provider',
            'environment',
        ],
    },
    {
        id: 'analytics',
        title: 'Analityka',
        description:
            'Konta, subskrypcje, konsultacje, wykorzystanie i przychody',
        group: 'Finanse',
        path: '/main/resources/analytics',
        roles: ['admin'],
        columns: [],
    },
    {
        id: 'cases',
        title: 'Sprawy',
        description: 'Szablony spraw, etapy i zadania',
        group: 'Legalizacja',
        path: '/main/legalization/cases',
        roles: ['admin', 'manager'],
        columns: ['title', 'status', 'lan', 'version'],
        hidden: false,
    },
    {
        id: 'case-types',
        title: 'Typy spraw',
        description: 'Kategorie procesów legalizacji',
        group: 'Legalizacja',
        path: '/main/legalization/types',
        roles: ['admin', 'manager'],
        columns: ['title', 'status', 'lan'],
        hidden: false,
    },
    {
        id: 'case-instructions',
        title: 'Instrukcje',
        description: 'Treści i zdjęcia instrukcji zadań',
        group: 'Legalizacja',
        path: '/main/legalization/instructions',
        roles: ['admin', 'manager'],
        columns: ['title', 'status', 'lan'],
        hidden: false,
    },
    {
        id: 'case-reminders',
        title: 'Szablony przypomnień',
        description: 'Wiadomości przypisane do zadań',
        group: 'Legalizacja',
        path: '/main/legalization/reminders',
        roles: ['admin', 'manager'],
        columns: ['topic', 'lan', 'sendInApp', 'sendEmail'],
        hidden: false,
    },
    {
        id: 'case-stages',
        title: 'Etapy',
        description: 'Etapy spraw i ich kolejność',
        group: 'Legalizacja',
        path: '/main/resources/case-stages',
        roles: ['admin', 'manager'],
        columns: ['stageNo', 'title', 'lan'],
        hidden: true,
    },
    {
        id: 'case-stage-tasks',
        title: 'Zadania',
        description: 'Zadania etapów i ich kolejność',
        group: 'Legalizacja',
        path: '/main/resources/case-stage-tasks',
        roles: ['admin', 'manager'],
        columns: ['sortKey', 'title', 'type'],
        hidden: true,
    },
    {
        id: 'case-instruction-blocks',
        title: 'Bloki instrukcji',
        description: 'Kolejność treści i obrazów',
        group: 'Legalizacja',
        path: '/main/resources/case-instruction-blocks',
        roles: ['admin', 'manager'],
        columns: ['sortKey', 'type'],
        hidden: true,
    },
    {
        id: 'users',
        title: 'Użytkownicy',
        description: 'Konta klientów i ich statusy',
        group: 'Ludzie',
        path: '/main/users',
        roles: ['admin', 'manager'],
        columns: ['name', 'surname', 'account.email', 'account.status'],
        hidden: false,
    },
    {
        id: 'specialists',
        title: 'Specjaliści',
        description: 'Profile ekspertów i weryfikacja',
        group: 'Ludzie',
        path: '/main/specialists',
        roles: ['admin', 'manager'],
        columns: ['name', 'surname', 'account.email', 'verified', 'rating'],
        hidden: false,
    },
    {
        id: 'managers',
        title: 'Zespół',
        description: 'Pracownicy CRM i przypisane role',
        group: 'Ludzie',
        path: '/main/managers',
        roles: ['admin'],
        columns: ['name', 'surname', 'account.email', 'position'],
        hidden: false,
    },
    {
        id: 'accounts',
        title: 'Konta',
        description: 'Dane kont i status dostępu',
        group: 'Ludzie',
        path: '/main/resources/accounts',
        roles: ['admin'],
        columns: ['email', 'type', 'status', 'lastLoginAt'],
        hidden: false,
    },
    {
        id: 'roles',
        title: 'Role',
        description: 'Role dostępne w organizacji',
        group: 'Ludzie',
        path: '/main/resources/roles',
        roles: ['admin'],
        columns: ['name', 'id'],
        hidden: false,
    },
    {
        id: 'blog-posts',
        title: 'Posty',
        description: 'Publikacje, kategorie i harmonogram',
        group: 'Treści',
        path: '/main/blog/posts',
        roles: [],
        columns: ['title', 'status', 'lan', 'publishedAt'],
        hidden: false,
    },
    {
        id: 'blog-categories',
        title: 'Kategorie bloga',
        description: 'Kategorie i kolejność wyświetlania',
        group: 'Treści',
        path: '/main/blog/categories',
        roles: [],
        columns: ['name_pl', 'name_ua', 'sort_key'],
        hidden: false,
    },
    {
        id: 'g-doc-templates',
        title: 'Szablony dokumentów',
        description: 'Pliki i zmienne dokumentów',
        group: 'Treści',
        path: '/main/documents/templates',
        roles: [],
        columns: ['titlePL', 'status', 'isPopular'],
        hidden: false,
    },
    {
        id: 'g-doc-types',
        title: 'Typy dokumentów',
        description: 'Katalog dokumentów',
        group: 'Treści',
        path: '/main/documents/types',
        roles: [],
        columns: ['titlePL', 'status', 'isPopular'],
        hidden: false,
    },
    {
        id: 'g-doc-vars',
        title: 'Zmienne dokumentów',
        description: 'Pola wykorzystywane w szablonach',
        group: 'Treści',
        path: '/main/documents/variables',
        roles: [],
        columns: ['key', 'labelPL'],
        hidden: false,
    },
    {
        id: 'public-assets',
        title: 'Ikony i pliki publiczne',
        description: 'Biblioteka zasobów publicznych',
        group: 'Biblioteka',
        path: '/main/icons',
        roles: [],
        columns: ['originalName', 'bucket', 'isPopular'],
        hidden: false,
    },
    {
        id: 'private-assets',
        title: 'Pliki prywatne',
        description: 'Biblioteka plików z kontrolą dostępu',
        group: 'Biblioteka',
        path: '/main/resources/private-assets',
        roles: [],
        columns: ['id', 'originalName', 'bucket', 'visibility'],
        hidden: false,
    },
    {
        id: 'private-variants',
        title: 'Zdjęcia',
        description: 'Obrazy i ich rozmiary do publikacji',
        group: 'Biblioteka',
        path: '/main/resources/private-variants',
        roles: [],
        columns: ['id', 'originalName', 'bucket'],
        hidden: false,
    },
    {
        id: 'consultation-bookings',
        title: 'Rezerwacje',
        description: 'Rezerwacje, spotkania, płatności i zwroty',
        group: 'Konsultacje',
        path: '/main/consultations',
        roles: ['admin', 'manager'],
        columns: [
            'id',
            'status',
            'startsAt',
            'refundStatus',
            'meetingStatus',
            'price',
            'currency',
        ],
        hidden: false,
    },
    {
        id: 'consultation-categories',
        title: 'Kategorie konsultacji',
        description: 'Tematy konsultacji i ich widoczność',
        group: 'Konsultacje',
        path: '/main/consultations/categories',
        roles: ['admin', 'manager'],
        columns: ['titlePl', 'isActive', 'isPopular'],
        hidden: false,
    },
    {
        id: 'specialist-consultations',
        title: 'Oferta specjalistów',
        description: 'Dostępne usługi i ceny',
        group: 'Konsultacje',
        path: '/main/resources/specialist-consultations',
        roles: ['admin', 'manager'],
        columns: ['id', 'specialistId', 'status'],
        hidden: false,
    },
    {
        id: 'consultation-reviews',
        title: 'Opinie',
        description: 'Moderacja opinii o konsultacjach',
        group: 'Konsultacje',
        path: '/main/resources/consultation-reviews',
        roles: ['admin', 'manager'],
        columns: ['id', 'rating', 'status', 'createdAt'],
        hidden: false,
    },
    {
        id: 'partners',
        title: 'Partnerzy',
        description: 'Konta partnerów i ich statusy',
        group: 'Partnerzy',
        path: '/main/partners',
        roles: ['admin', 'manager', 'marketolog'],
        columns: ['name', 'surname', 'account.email'],
        hidden: false,
    },
    {
        id: 'partner-companies',
        title: 'Firmy',
        description: 'Profile firm, logotypy i statusy',
        group: 'Partnerzy',
        path: '/main/resources/partner-companies',
        roles: ['admin', 'manager', 'marketolog'],
        columns: ['name', 'status', 'id'],
        hidden: false,
    },
    {
        id: 'partner-company-info',
        title: 'Informacje o firmie',
        description: 'Opisy, zdjęcia i sieci społecznościowe',
        group: 'Partnerzy',
        path: '/main/resources/partner-company-info',
        roles: ['admin', 'manager', 'marketolog'],
        columns: ['id'],
        hidden: true,
    },
    {
        id: 'partner-banners',
        title: 'Reklamy partnerów',
        description: 'Moderacja i harmonogram reklam',
        group: 'Partnerzy',
        path: '/main/resources/partner-banners',
        roles: ['admin', 'manager', 'marketolog'],
        columns: ['id', 'status', 'createdAt'],
        hidden: false,
    },
    {
        id: 'promocodes',
        title: 'Kody promocyjne',
        description: 'Rabaty, ograniczenia i historia użycia',
        group: 'Promocje',
        path: '/main/promocodes',
        roles: ['admin'],
        columns: ['code', 'type', 'value', 'status'],
        hidden: false,
    },
    {
        id: 'consultation-promocodes',
        title: 'Promocje konsultacji',
        description: 'Powiązanie kodów z konsultacjami',
        group: 'Promocje',
        path: '/main/resources/consultation-promocodes',
        roles: ['admin'],
        columns: ['id', 'promocodeId'],
        hidden: false,
    },
    {
        id: 'mail-jobs',
        title: 'Kampanie e-mail',
        description: 'Odbiorcy, załączniki i harmonogram wysyłki',
        group: 'Komunikacja',
        path: '/main/mail/jobs',
        roles: ['writer'],
        columns: ['title', 'status', 'subject', 'deliverAt'],
        hidden: false,
    },
    {
        id: 'mail',
        title: 'Wyślij e-mail',
        description: 'Wiadomość bezpośrednia',
        group: 'Komunikacja',
        path: '/main/mail',
        roles: ['writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'mail-signatures',
        title: 'Podpisy e-mail',
        description: 'Logo i dane firmy dołączane do wiadomości',
        group: 'Komunikacja',
        path: '/main/resources/mail-signatures',
        roles: ['writer'],
        columns: ['title', 'companyName', 'email'],
        hidden: false,
    },
    {
        id: 'mail-snippets',
        title: 'Szablony e-mail',
        description: 'Treści wielokrotnego użytku',
        group: 'Komunikacja',
        path: '/main/resources/mail-snippets',
        roles: ['writer'],
        columns: ['title', 'subject'],
        hidden: false,
    },
    {
        id: 'mail-accounts',
        title: 'Skrzynki pocztowe',
        description: 'Konfiguracja nadawców i limity',
        group: 'Komunikacja',
        path: '/main/resources/mail-accounts',
        roles: ['writer'],
        columns: ['fromName', 'fromEmail', 'provider'],
        hidden: false,
    },
    {
        id: 'user-notification-jobs',
        title: 'Kampanie powiadomień',
        description: 'Odbiorcy i harmonogram powiadomień',
        group: 'Komunikacja',
        path: '/main/notifications',
        roles: ['admin', 'manager', 'writer'],
        columns: ['title', 'status', 'subject', 'deliverAt'],
        hidden: false,
    },
    {
        id: 'user-notifications',
        title: 'Wyślij powiadomienie',
        description: 'Wiadomość do konkretnego użytkownika',
        group: 'Komunikacja',
        path: '/main/resources/user-notifications',
        roles: ['admin', 'writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'user-reminders',
        title: 'Przypomnienia',
        description: 'Przypomnienia dla użytkownika i zadania',
        group: 'Komunikacja',
        path: '/main/reminders',
        roles: ['admin', 'manager', 'writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'mail-queue',
        title: 'Kolejka e-mail',
        description: 'Uruchomienie przetwarzania kolejki',
        group: 'Automatyzacja',
        path: '/main/resources/mail-queue',
        roles: ['writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'user-notification-queue',
        title: 'Kolejka powiadomień',
        description: 'Uruchomienie wysyłki powiadomień',
        group: 'Automatyzacja',
        path: '/main/resources/user-notification-queue',
        roles: ['admin', 'writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'user-reminder-events',
        title: 'Zdarzenia przypomnień',
        description: 'Przetwarzanie zaplanowanych przypomnień',
        group: 'Automatyzacja',
        path: '/main/resources/user-reminder-events',
        roles: ['admin', 'manager', 'writer'],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'account-auth',
        title: 'Bezpieczeństwo',
        description: 'Zmiana hasła i adresu e-mail',
        group: 'Konto',
        path: '/main/resources/account-auth',
        roles: [],
        columns: ['id'],
        hidden: false,
    },
    {
        id: 'files',
        title: 'Pobierz plik',
        description: 'Pobieranie podpisanego pliku',
        group: 'Biblioteka',
        path: '/main/resources/files',
        roles: [],
        columns: ['id'],
        hidden: true,
    },
]

export function getResource(id: string) {
    return resources.find((resource) => resource.id === id)
}

export function resourceForPath(path: string) {
    return resources
        .filter(
            (resource) =>
                path === resource.path || path.startsWith(`${resource.path}/`),
        )
        .sort((a, b) => b.path.length - a.path.length)[0]
}
