export const operationLabels: Record<string, string> = {
    retryOperations: 'Ponów operacje',
    cancelByAdmin: 'Anuluj rezerwację',
    retire: 'Wycofaj',
    trialSettings: 'Okres próbny',
    updateTrialSettings: 'Zmień okres próbny',
    publish: 'Opublikuj PDF',
    downloadDraft: 'Pobierz szkic PDF',
    simulate: 'Symuluj zdarzenie',
    overview: 'Przegląd',
    subscriptions: 'Subskrypcje',
    consultations: 'Konsultacje',
    usage: 'Wykorzystanie',
    revenue: 'Przychody',

    create: 'Dodaj',
    register: 'Dodaj konto',
    update: 'Edytuj',
    remove: 'Usuń',
    getById: 'Otwórz',
    list: 'Lista',
    reorder: 'Zmień kolejność',
    copy: 'Utwórz kopię',
    schedule: 'Zaplanuj',
    cancel: 'Anuluj wysyłkę',
    approve: 'Zatwierdź',
    reject: 'Odrzuć',
    activate: 'Aktywuj',
    deactivate: 'Dezaktywuj',
    finish: 'Zakończ',
    updateStatus: 'Zmień status',
    updateRoles: 'Zmień role',
    uploadLogo: 'Zmień logo',
    uploadPhoto: 'Zmień zdjęcie',
    download: 'Pobierz plik',
    togglePopular: 'Zmień wyróżnienie',
    getUrl: 'Pokaż link do pliku',
    setAccounts: 'Ustaw uprawnione konta',
    listAccounts: 'Uprawnione konta',
    listUsages: 'Historia użycia',
    send: 'Wyślij wiadomość',
    progress: 'Postęp wysyłki',
    build: 'Przygotuj odbiorców',
    tick: 'Przetwórz kolejkę',
    getMe: 'Mój profil',
    updateMe: 'Edytuj profil',
    listByCase: 'Etapy sprawy',
    listByStage: 'Zadania etapu',
    listByInstruction: 'Bloki instrukcji',
    requestEmailChange: 'Wyślij kod zmiany e-mail',
    confirmEmailChange: 'Potwierdź nowy e-mail',
    requestPasswordChange: 'Wyślij kod zmiany hasła',
    changePassword: 'Zmień hasło',
    confirm: 'Potwierdź konto',
    resend: 'Wyślij ponownie kod',
    login: 'Zaloguj',
    forgotPassword: 'Wyślij kod resetowania',
    resetPassword: 'Ustaw nowe hasło',
}

const names: Record<string, string> = {
    planId: 'Plan subskrypcji',
    priceId: 'Cena subskrypcji',
    subscriptionPlanId: 'Plan w momencie zakupu',
    rank: 'Pozycja planu',
    documentsPerMonth: 'Dokumenty na miesiąc',
    openCases: 'Otwarte sprawy',
    retentionMonths: 'Przechowywanie dokumentów (miesiące)',
    consultationDiscountPercent: 'Rabat na konsultacje (%)',
    available: 'Dostępne',
    days: 'Liczba dni',
    enabled: 'Włączone',
    interval: 'Okres rozliczeniowy',
    productId: 'ID produktu u dostawcy',
    basePlanId: 'ID planu bazowego Google',
    eventId: 'ID zdarzenia (unikalne)',
    legalAcceptanceId: 'ID akceptacji warunków',
    legalVersionIds: 'Wersje zaakceptowanych dokumentów',
    isPlaceholder: 'Dokument zastępczy',
    versionId: 'Wersja dokumentu',
    documentId: 'Dokument',
    placement: 'Miejsce użycia',
    sha256: 'Suma kontrolna SHA-256',
    from: 'Od (UTC)',
    to: 'Do (UTC, bez tego dnia)',
    group: 'Grupowanie',
    amountMinor: 'Kwota (najmniejsza jednostka)',
    environment: 'Środowisko',
    kind: 'Rodzaj',
    product: 'Produkt',
    paymentProvider: 'Dostawca płatności',
    refundStatus: 'Status zwrotu',
    meetingStatus: 'Status spotkania',
    meetingUrl: 'Link do spotkania',
    refundReference: 'ID zwrotu',
    refundedAt: 'Zwrócono',
    paidAt: 'Opłacono',
    withdrawalUntil: 'Termin odstąpienia',
    earlyServiceConsentAt: 'Zgoda na wcześniejszą realizację',
    originalStartsAt: 'Pierwotny termin',
    canceledAt: 'Anulowano',
    subscriptionDiscountPercent: 'Rabat z subskrypcji (%)',
    revision: 'Rewizja',
    fileDeletedAt: 'Plik usunięto',
    registrations: 'Rejestracje',
    plans: 'Plany',
    trialCohort: 'Konwersja okresu próbnego',
    events: 'Zdarzenia',
    bookingsByCurrentStatus: 'Rezerwacje według statusu',
    purchases: 'Zakupy',
    refunds: 'Zwroty',
    specialists: 'Specjaliści',
    products: 'Produkty',
    generations: 'Wygenerowane dokumenty',
    casesCreated: 'Utworzone sprawy',
    currentCases: 'Aktualne sprawy',
    currentQuotas: 'Wykorzystanie limitów',
    amounts: 'Kwoty według walut',
    series: 'Przebieg w czasie',
    sandbox: 'Transakcje sandbox',
    devConsultations: 'Symulowane konsultacje',
    devSubscriptionEvents: 'Testowe zdarzenia subskrypcji',
    period: 'Okres',
    count: 'Liczba',
    trials: 'Okresy próbne',
    paidAccess: 'Płatny dostęp',
    paymentsMinor: 'Wpłaty (najmniejsza jednostka)',
    refundsMinor: 'Zwroty (najmniejsza jednostka)',
    afterRefundsMinor: 'Po zwrotach (najmniejsza jednostka)',
    operations: 'Operacje',
    usedDocuments: 'Wykorzystane dokumenty',
    exhausted: 'Wyczerpane limity',
    started: 'Rozpoczęte',
    converted: 'Przekształcone w płatne',
    conversionPercent: 'Konwersja (%)',
    dto: 'Dane',
    categories: 'Kategorie',
    roles: 'Role',
    account: 'Konto',
    accounts: 'Konta',
    info: 'Profil',
    stages: 'Etapy',
    tasks: 'Zadania',
    variant: 'Zdjęcie',
    icon: 'Ikona',
    caseType: 'Typ sprawy',
    query: 'Filtry',
    id: 'ID',
    title: 'Tytuł',
    name: 'Nazwa',
    surname: 'Nazwisko',
    email: 'E-mail',
    phone: 'Telefon',
    status: 'Status',
    type: 'Typ',
    lan: 'Język',
    language: 'Język',
    topic: 'Temat',
    subject: 'Temat',
    text: 'Treść',
    contentJson: 'Treść',
    description: 'Opis',
    shortDescription: 'Krótki opis',
    subtitle: 'Podtytuł',
    password: 'Hasło',
    currentPassword: 'Obecne hasło',
    newEmail: 'Nowy e-mail',
    code: 'Kod',
    createdAt: 'Utworzono',
    updatedAt: 'Zmieniono',
    publishedAt: 'Opublikowano',
    scheduledAt: 'Data publikacji',
    deliverAt: 'Termin wysyłki',
    targetAt: 'Termin przypomnienia',
    startsAt: 'Początek',
    expiresAt: 'Wygaśnięcie',
    endsAt: 'Koniec',
    isActive: 'Aktywne',
    isPopular: 'Wyróżnione',
    isPinned: 'Przypięte',
    verified: 'Zweryfikowany',
    accountId: 'Konto',
    accountIds: 'Konta',
    userId: 'Użytkownik',
    userTaskId: 'Zadanie użytkownika',
    specialistId: 'Specjalista',
    partnerId: 'Partner',
    companyId: 'Firma',
    caseId: 'Sprawa',
    stageId: 'Etap',
    instructionId: 'Instrukcja',
    reminderId: 'Przypomnienie',
    typeId: 'Typ sprawy',
    categoryId: 'Kategoria',
    categoryIds: 'Kategorie',
    roleIds: 'Role',
    iconId: 'Ikona',
    headerIconId: 'Ikona nagłówka',
    variantId: 'Zdjęcie',
    avatarId: 'Awatar',
    assetId: 'Plik',
    mediaAssetId: 'Plik',
    templateId: 'Szablon',
    titlePL: 'Tytuł · PL',
    name_pl: 'Nazwa · PL',
    labelPL: 'Etykieta · PL',
    key: 'Klucz',
    version: 'Wersja',
    page: 'Strona',
    limit: 'Na stronie',
    offset: 'Przesunięcie',
    q: 'Szukaj',
    search: 'Szukaj',
    value: 'Wartość',
    currency: 'Waluta',
    productType: 'Produkt',
    restrictedAccounts: 'Tylko wybrane konta',
    maxRedemptions: 'Limit użyć',
    perAccountLimit: 'Limit na konto',
    notes: 'Notatki',
    file: 'Plik',
    originalName: 'Nazwa pliku',
    bucket: 'Przeznaczenie',
    visibility: 'Widoczność',
    accountTypes: 'Typy kont',
    audience: 'Odbiorcy',
    attachments: 'Załączniki',
    inlineImages: 'Obrazy w wiadomości',
    html: 'Treść HTML',
    filename: 'Nazwa załącznika',
    cid: 'Identyfikator obrazu',
    sendInApp: 'Wyślij w aplikacji',
    sendEmail: 'Wyślij e-mail',
    direction: 'Kierunek',
    fromName: 'Nazwa nadawcy',
    fromEmail: 'Adres nadawcy',
    provider: 'Dostawca',
    sortKey: 'Kolejność',
    sort_key: 'Kolejność',
    stageNo: 'Numer etapu',
    position: 'Stanowisko',
    location: 'Lokalizacja',
    rating: 'Ocena',
    reason: 'Powód',
    rejectionReason: 'Powód odrzucenia',
    comment: 'Komentarz',
    ownerAccountId: 'Właściciel',
    theme: 'Motyw',
    websiteUrl: 'Strona internetowa',
}

export function label(key: string): string {
    if (names[key]) return names[key]

    const translated = key.match(/^(.*?)(?:_)?(ua|pl|ru|en)$/i)

    if (translated && names[translated[1]])
        return `${names[translated[1]]} · ${translated[2].toUpperCase()}`

    return key
        .replace(/([a-z])([A-Z])/g, '$1 $2')
        .replaceAll('_', ' ')
        .replace(/^./, (value) => value.toUpperCase())
}

const values: Record<string, string> = {
    registration_terms: 'Regulamin rejestracji',
    privacy_policy: 'Polityka prywatności',
    subscription_terms: 'Regulamin subskrypcji',
    consultation_terms: 'Regulamin konsultacji',
    specialist_terms: 'Regulamin specjalistów',
    partner_terms: 'Regulamin partnerów',
    production: 'Produkcja',
    sandbox: 'Sandbox',
    dev: 'Deweloperski',
    monthly: 'Miesięczny',
    yearly: 'Roczny',
    day: 'Dzień',
    month: 'Miesiąc',
    trial: 'Okres próbny',
    revoked: 'Odebrane',
    canceled: 'Anulowane',
    succeeded: 'Zakończone poprawnie',
    failed: 'Nieudane',
    ready: 'Gotowe',
    none: 'Brak',
    purchase: 'Zakup',
    renew: 'Odnowienie',
    upgrade: 'Zmiana na wyższy plan',
    schedule: 'Zaplanuj zmianę',
    cancel: 'Wyłącz odnowienie',
    resume: 'Włącz odnowienie',
    expire: 'Wygaśnięcie',
    revoke: 'Odbierz dostęp',

    active: 'Aktywne',
    draft: 'Szkic',
    archived: 'Archiwum',
    pending: 'Oczekujące',
    blocked: 'Zablokowane',
    inactive: 'Nieaktywne',
    scheduled: 'Zaplanowane',
    published: 'Opublikowane',
    running: 'W toku',
    done: 'Zakończone',
    cancelled: 'Anulowane',
    approved: 'Zatwierdzone',
    rejected: 'Odrzucone',
    true: 'Tak',
    false: 'Nie',
    up: 'W górę',
    down: 'W dół',
    white: 'Jasny',
    black: 'Ciemny',
    percent: 'Procent',
    amount: 'Kwota',
    info: 'Informacja',
    text: 'Tekst',
    photo: 'Zdjęcie',
    with_date: 'Z terminem',
}

export function valueLabel(value: unknown) {
    return values[String(value)] ?? String(value ?? '—')
}
